# Generated by Django 5.1.6 on 2025-02-19 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_card_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='response',
            new_name='responsible',
        ),
    ]
